name: Deploy pages
on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Build
        run: npm run build_prod
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' # Authorize the deployment for the main branch only
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
